# 开发环境配置

# OpenAI配置
openai:
  api_key: ${OPENAI_API_KEY}
  model: gpt-4-turbo-preview
  temperature: 0.0

# Agent配置
agent:
  enable_cache: true
  max_retries: 3
  timeout: 30

# TTS配置
tts:
  enable: false
  provider: edge
  voice: zh-CN-XiaoxiaoNeural
  rate: +0%
  volume: +0%

# 日志配置
logging:
  level: DEBUG
  file: logs/development.log

# 环境
environment: development
debug: true
